// <auto-generated />
using System;
using ClientHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820135811_AddClientOwnerAndSeedData")]
    partial class AddClientOwnerAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClientHub.Models.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PostalCodeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PostalCodeId");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Rua Augusta, 100",
                            CreatedAt = new DateTime(2026, 8, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Email = "john.smith@example.com",
                            FirstName = "John",
                            LastName = "Smith",
                            Phone = "+351 912 345 001",
                            PostalCodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Avenida da Liberdade, 200",
                            CreatedAt = new DateTime(2026, 8, 14, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Email = "maria.silva@example.com",
                            FirstName = "Maria",
                            LastName = "Silva",
                            Phone = "+351 965 432 109",
                            PostalCodeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rua Ferreira Borges, 300",
                            CreatedAt = new DateTime(2026, 8, 12, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Email = "pedro.santos@example.com",
                            FirstName = "Pedro",
                            LastName = "Santos",
                            Phone = "+351 961 234 567",
                            PostalCodeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "Praça do Município, 400",
                            CreatedAt = new DateTime(2026, 8, 10, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Email = "ana.souza@example.com",
                            FirstName = "Ana",
                            LastName = "Souza",
                            Phone = "+351 917 654 321",
                            PostalCodeId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 8, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByUserId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Email = "carlos.oliveira@example.com",
                            FirstName = "Carlos",
                            LastName = "Oliveira",
                            Phone = "+351 969 876 543",
                            PostalCodeId = 5
                        });
                });

            modelBuilder.Entity("ClientHub.Models.Entities.PostalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PostalCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Lisboa",
                            Code = "1000-001"
                        },
                        new
                        {
                            Id = 2,
                            City = "Porto",
                            Code = "4000-100"
                        },
                        new
                        {
                            Id = 3,
                            City = "Coimbra",
                            Code = "3000-000"
                        },
                        new
                        {
                            Id = 4,
                            City = "Braga",
                            Code = "4700-000"
                        },
                        new
                        {
                            Id = 5,
                            City = "Faro",
                            Code = "8000-000"
                        },
                        new
                        {
                            Id = 6,
                            City = "Aveiro",
                            Code = "3800-000"
                        },
                        new
                        {
                            Id = 7,
                            City = "Évora",
                            Code = "7000-000"
                        },
                        new
                        {
                            Id = 8,
                            City = "Setúbal",
                            Code = "2900-000"
                        },
                        new
                        {
                            Id = 9,
                            City = "Funchal",
                            Code = "9000-000"
                        },
                        new
                        {
                            Id = 10,
                            City = "Ponta Delgada",
                            Code = "9500-000"
                        });
                });

            modelBuilder.Entity("ClientHub.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "demo@clienthub.dev",
                            PasswordHash = "AQAAAAIAAYagAAAAEDurHBiNUlg+IflHWRfQNTbsgriWYFY65X9z6wjkLpc7jTv+nqk4yZTtATQR6XNdVA=="
                        });
                });

            modelBuilder.Entity("ClientHub.Models.Entities.Client", b =>
                {
                    b.HasOne("ClientHub.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClientHub.Models.Entities.PostalCode", "PostalCode")
                        .WithMany("Clients")
                        .HasForeignKey("PostalCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("PostalCode");
                });

            modelBuilder.Entity("ClientHub.Models.Entities.PostalCode", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
